[package]
name = "rust-s3-async-ffi"
version = "0.2.1"
edition = "2021"

[dependencies]
tokio = {version = "1.27.0", features = ["macros", "rt-multi-thread"]}
rust-s3 = "0.34.0-rc4"
ffi-convert = "0.6.1"
ffi-convert-derive = "0.6.1"
futures = "0.3.28"
serde = "1.0.159"
errno = "0.3.1"
nix = "0.26.2"

[dev-dependencies]
config = "0.13.3"
chrono = "0.4.24"

[lib]
name = "rusts3asyncffi"
path = "src/lib.rs"
crate-type = ["cdylib"]

