name: CI
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Localstack
        uses: LocalStack/setup-localstack@main
        with:
          image-tag: 'latest'
          install-awslocal: 'true'
      - name: Configure bucket
        run: |
          aws configure --profile default \
              set aws_access_key_id test-rust-s3-async-ffi
          aws configure --profile default \
              set aws_secret_access_key test-rust-s3-async-ffi
          aws configure --profile default \
              set default.region eu-central-1
          aws s3 mb s3://my-bucket --endpoint-url http://localhost:4566
      - name: Cargo build
        run: cargo build
      - name: Cargo test
        run: |
          cargo test -- --nocapture
          aws s3 ls s3://my-bucket --endpoint-url http://localhost:4566
      - name: Install Boost libraries
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libboost-all-dev
      - name: Asio test
        run: |
          cd test/asio
          make
          LD_LIBRARY_PATH=../../target/debug ./s3_async_test \
              -p /data/object_asio.data
          aws s3 ls s3://my-bucket --endpoint-url http://localhost:4566
          cd -

